#!/usr/bin/env bash

# Output to stdout if we aren't on a runner
if [ -z "${GITHUB_OUTPUT}" ]; then
    GITHUB_OUTPUT="/dev/stdout"
fi

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"

if [ "${#}" -ne 1 ]; then
    printf "Usage: %s ARTIFACT_DIR\n" "${0}" >&2
    exit 1
fi
ARTIFACT_DIR="${1}"
if [ ! -d "${ARTIFACT_DIR}" ]; then
    failure "Invalid path provided for artifact directory (%s)" "${ARTIFACT_DIR}"
fi

pushd "${ARTIFACT_DIR}"

g_files=( ./vagrant*.gem )
gem_file="${g_files[0]}"
if [ ! -f "${gem_file}" ]; then
    failure "Failed to detect expected Vagrant RubyGem file (%s)" "${g_files[*]}"
fi

# Get the Vagrant version from the gem
spec_info="$(gem spec "${gem_file}" version)" ||
    failure "Unable to read version information from Vagrant RubyGem"
vagrant_version="${spec_info##*: }"
# Generate the shasum of the gem
sha_info="$(sha1sum "${gem_file}")" ||
    failure "Unable to generate shasum for Vagrant RubyGem"
vagrant_sha="${sha_info%% *}"

# Write the outputs
printf "vagrant-version=%s\n" "${vagrant_version}" >> "${GITHUB_OUTPUT}"
printf "vagrant-shasum=%s\n" "${vagrant_sha}" >> "${GITHUB_OUTPUT}"
