#!/usr/bin/env bash

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"
pushd "${root}"

# Output to stdout if we aren't on a runner
if [ -z "${GITHUB_OUTPUT}" ]; then
    GITHUB_OUTPUT="/dev/stdout"
fi

if [ "${#}" -ne 3 ]; then
    printf "Usage: %s VERSION GEM_SHA RUN_ID\n" "${0}" >&2
    exit 1
fi

version="${1}"
sha="${2}"
run_id="${3}"

if [ -z "${version}" ]; then
    failure "Vagrant version is required"
fi
if [ -z "${sha}" ]; then
    failure "Vagrant RubyGem shasum is required"
fi
if [ -z "${run_id}" ]; then
    failure "Run identifier is required"
fi

# Create the name for the nightly release
nightly_name="${version}+${run_id}-${sha:0:7}"
debug "nightly release name: %s" "${nightly_name}"

# Create the output for the release name
printf "release-name=%s\n" "${nightly_name}" >> "${GITHUB_OUTPUT}"

# Check if the nightly already exists
if github_release_exists "vagrant" "${nightly_name}"; then
    debug "nightly release '%s' already exists" "${nightly_name}"
    printf "release-exists=true\n" >> "${GITHUB_OUTPUT}"
fi
