#!/usr/bin/env bash

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"
pushd "${root}"

# Output to stdout if we aren't on a runner
if [ -z "${GITHUB_OUTPUT}" ]; then
    GITHUB_OUTPUT="/dev/stdout"
fi

if [ "${#}" -ne 2 ]; then
    printf "Usage: %s VERSION ARTIFACT_DIR\n" "${0}" >&2
    exit 1
fi

tag_name="${1}"
pkg_dir="${2}"

if [ -z "${tag_name}" ]; then
    failure "Tag name is required for local publish"
fi

if [ -z "${pkg_dir}" ]; then
    failure "Package artifact directory is required for local publish"
fi

if [[ "${tag_name}" != *"+"* ]]; then
    tag_name="${tag_name}+${short_sha}"
fi

debug "creating local prerelease %s" "${tag_name}"

if github_release_exists "${repo_name}" "${tag_name}"; then
    warn "Local dev build (%s) already exists, removing..." "${tag_name}"
    github_delete_release "${tag_name}" "${repo_name}"
fi

prerelease "${tag_name}" "${pkg_dir}"
