#!/usr/bin/env bash

# Output to stdout if we aren't on a runner
if [ -z "${GITHUB_OUTPUT}" ]; then
    GITHUB_OUTPUT="/dev/stdout"
fi

csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../" && pwd )"

. "${root}/.ci/load-ci.sh"
pushd "${root}"

# Generate substrate information

run_sha="$(git log --format=%h -1 ./substrate/run.sh)" ||
    failure "Could not generate commit sha for ./substrate/run.sh"
deps_sha="$(git log --format=%h -1 ./substrate/deps.sh)" ||
    failure "Could not generate commit sha for ./substrate/deps.sh"

sub_cache_base="substrate-${run_sha}+${deps_sha}"

sub32="rpm-${sub_cache_base}-32"
printf "rpm-32-substrate-id=%s\n" "${sub32}" >> "${GITHUB_OUTPUT}"
if github_draft_release_exists "${repo_name}" "${sub32}"; then
    printf "rpm-32-substrate-exists=true\n" >> "${GITHUB_OUTPUT}"
fi
sub64="rpm-${sub_cache_base}-64"
printf "rpm-64-substrate-id=%s\n" "${sub64}" >> "${GITHUB_OUTPUT}"
if github_draft_release_exists "${repo_name}" "${sub64}"; then
    printf "rpm-64-substrate-exists=true\n" >> "${GITHUB_OUTPUT}"
fi

pkg_sha="$(git log --format=%h -1 ./package/build-rpm)" ||
    failure "Could not generate commit sha for ./package/build-rpm"
pkg_support_sha="$(git log --format=%h -1 ./package/support/rpm)" ||
    failure "Could not generate commit sha for ./package/support/rpm"
vagrant_sha="${VAGRANT_SHASUM:0:10}"
pkg_base="${vagrant_sha}+${pkg_sha}+${pkg_support_sha}"

inst32="rpm-install-${pkg_base}-32"
printf "rpm-32-install-id=%s\n" "${inst32}" >> "${GITHUB_OUTPUT}"
if github_draft_release_exists "${repo_name}" "${inst32}"; then
    printf "rpm-32-install-exists=true\n" >> "${GITHUB_OUTPUT}"
fi
inst64="rpm-install-${pkg_base}-64"
printf "rpm-64-install-id=%s\n" "${inst64}" >> "${GITHUB_OUTPUT}"
if github_draft_release_exists "${repo_name}" "${inst64}"; then
    printf "rpm-64-install-exists=true\n" >> "${GITHUB_OUTPUT}"
fi

pkgs="rpm-pkgs-${pkg_base}"
printf "rpm-packages-id=%s\n" "${pkgs}" >> "${GITHUB_OUTPUT}"
if github_draft_release_exists "${repo_name}" "${pkgs}"; then
    printf "rpm-packages-exists=true\n" >> "${GITHUB_OUTPUT}"
fi
