#!/usr/bin/env bash

prefix="${1?Prefix required}"

# Update and reinstall packages that are broken due to missing dependencies
# on initial bootstrap

chroot "${prefix}" yum update -y -q binutils coreutils gawk initscripts krb5-libs \
    libcurl ncurses openldap util-linux yum elfutils-libs glib2 yum-utils rpm

chroot "${prefix}" yum reinstall -y -q crontabs ncurses-libs neon openssl-libs pam pygpgme
