#!/usr/bin/env bash

# This script should not be called directly. It handles
# doing the internal setup of the centos chroot

# Load CI helpers
csource="${BASH_SOURCE[0]}"
while [ -h "$csource" ] ; do csource="$(readlink "$csource")"; done
root="$( cd -P "$( dirname "$csource" )/../../" && pwd )"

. "${root}/.ci/load-ci.sh"

if [ "$(id -u)" != "0" ]; then
    failure "Script must be run as root"
fi

# Now do an intial update
debug "running system update"
yum update -y

# Install base tooling
debug "installing base tools"
yum groupinstall -y "development tools" || exit
yum install -y \
    autoconf \
    curl \
    git \
    make \
    perl \
    python-devel \
    tar || exit

# Now install updated build tools
debug "installing build tools"

yum install -y \
    chrpath \
    devtoolset-8-toolchain \
    gcc \
    rh-perl524 \
    rh-perl524-perl-IPC-Cmd \
    rh-perl524-perl-open \
    rh-perl524-perl-Data-Dumper \
    rh-perl524-perl-Thread-Queue \
    python27 \
    glibc-*.i686 \
    libgcc-*.i686 \
    libstdc++-*.i686 || exit

# Enable the updated versions
echo '. /opt/rh/devtoolset-8/enable' >> /etc/profile
echo '. /opt/rh/rh-perl524/enable' >> /etc/profile
echo '. /opt/rh/python27/enable' >> /etc/profile

debug "enabling new dev tools for auto builds"
. /opt/rh/devtoolset-8/enable
. /opt/rh/rh-perl524/enable
. /opt/rh/python27/enable
