#!/usr/bin/env bash

prefix="${1?Prefix required}"

pushd "${prefix}/etc/yum.repos.d" || exit

# Delete all the repo configurations
echo "Deleting all existing centos repository configurations"
rm -f ./*.repo

# Install custom configuration
cat <<EOF > centos.repo
[CS7-base]
name=CentOS-7 - Base
baseurl=http://archive.kernel.org/centos-vault/centos/7/os/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

[CS7-updates]
name=CentOS-7 - Updates
baseurl=http://archive.kernel.org/centos-vault/centos/7/updates/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

[CS7-extras]
name=CentOS-7 - Extras
baseurl=http://archive.kernel.org/centos-vault/centos/7/extras/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

[CS7-plus]
name=CentOS-7 - CentOSPlus
baseurl=http://archive.kernel.org/centos-vault/centos/7/centosplus/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

[CS7-fasttrack]
name=CentOS-7 - Fasttrack
baseurl=http://archive.kernel.org/centos-vault/centos/7/fasttrack/\$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1

[CS7-sclo]
name=CentOS-7 - SCLo rh
baseurl=http://archive.kernel.org/centos-vault/centos/7/sclo/\$basearch/rh
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo
enabled=1
EOF

echo "Wrote new centos repository configuration - $(pwd)"
ls -lah

popd || exit
