on:
  push:
    branches:
      - 'main'
    paths:
      - 'packer/vagrant/template_centos-7-i386.json'
      - 'packer/vagrant/scripts/centos/**'
  workflow_dispatch:
    branches:
          - 'main'

jobs:
  build:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Build Vagrant Installer Boxes (centos 386)
    runs-on: self-hosted
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Build Box
        run: ./.ci/build-boxes.sh
        working-directory: ${{github.workspace}}
        env:
          PKT_PACKER_BUILDS: "centos-7-i386"
          VAGRANT_CI_LOADER_BUCKET: ${{ secrets.VAGRANT_CI_LOADER_BUCKET }}
      - name: Clean Workspace
        if: always()
        run: rm -rf ${{ github.workspace }}
