on:
  push:
    branches:
      - 'main'
      - 'box-ubuntu-*'
    paths:
      - 'packer/vagrant/template_ubuntu-14.04.json'
      - 'packer/vagrant/scripts/ubuntu/**'
  schedule:
    - cron: '30 2 5 * *'
  workflow_dispatch:
    branches:
      - 'main'

concurrency: boxes-${{ github.ref_name }}

env:
  PACKET_EXEC_DEVICE_NAME: ci-boxes-${{ github.ref_name }}

jobs:
  build:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Build Vagrant Installer Boxes (ubuntu)
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot token | hashibot_token;
            kv/data/teams/vagrant/packet token | packet_token;
            kv/data/teams/vagrant/packet project_id | packet_project_id;
            kv/data/teams/vagrant/packet ssh_key_content | packet_ssh_key_content;
            kv/data/teams/vagrant/vagrantcloud token | vagrant_cloud_token;
            kv/data/teams/vagrant/slack webhook | slack_webhook;
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Build Box
        run: ./.ci/build-boxes.sh
        working-directory: ${{github.workspace}}
        env:
          PKT_PACKER_BUILDS: "ubuntu-14.04"
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.hashibot_token }}
          PACKET_EXEC_TOKEN: ${{ steps.secrets.outputs.packet_token }}
          PACKET_EXEC_PROJECT_ID: ${{ steps.secrets.outputs.packet_project_id }}
          PACKET_SSH_KEY_CONTENT: ${{ steps.secrets.outputs.packet_ssh_key_content }}
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.slack_webhook }}
          VAGRANT_CLOUD_TOKEN: ${{ steps.secrets.outputs.vagrant_cloud_token }}
      - name: Clean Workspace
        if: always()
        run: rm -rf ${{ github.workspace }}
