on:
  push:
    branches:
      - 'main'
      - 'box-archlinux-*'
    paths:
      - 'packer/vagrant/template_archlinux.json'
      - 'packer/vagrant/scripts/arch/**'
  schedule:
    - cron: '30 2 7 * *'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  slack-vars:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Populate vars
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.nano']
    uses: ./.github/workflows/slack-vars.yml
    packet-vars:
      if: github.repository == 'hashicorp/vagrant-builders'
    name: Populate vars
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.nano']
    uses: ./.github/workflows/packet-vars.yml
  build:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Build Vagrant Installer Boxes (archlinux)
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.nano']
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Build Box
        run: ./.ci/build-boxes.sh
        working-directory: ${{github.workspace}}
        env:
          PKT_PACKER_BUILDS: "archlinux"
          PACKET_EXEC_TOKEN: ${{ needs.packet-vars.outputs.PACKET_EXEC_TOKEN }}
          PACKET_EXEC_PROJECT_ID: ${{ needs.packet-vars.outputs.PACKET_EXEC_PROJECT_ID }}
          PACKET_SSH_KEY_CONTENT: ${{ needs.packet-vars.outputs.PACKET_SSH_KEY_CONTENT }}
          SLACK_WEBHOOK: ${{ needs.slack-vars.outputs.SLACK_WEBHOOK }}
          VAGRANT_CLOUD_TOKEN: ${{ needs.vagrantcloud-vars.outputs.VAGRANT_CLOUD_TOKEN }}
      - name: Clean Workspace
        if: always()
        run: rm -rf ${{ github.workspace }}
