name: Vagrant DEB Builder
on:
  workflow_call:
    inputs:
      vagrant-artifacts-name:
        description: Name of upload containing Vagrant build artifacts
        required: true
        type: string
      vagrant-artifacts-path:
        description: Path used for Vagrant build artifacts
        required: true
        type: string
      vagrant-gem-name:
        description: Name of upload containing the Vagrant RubyGem
        required: true
        type: string
      vagrant-gem-path:
        description: Path used for the Vagrant RubyGem (directory)
        required: true
        type: string
      vagrant-version:
        description: Version of Vagrant being built
        required: true
        type: string
      vagrant-shasum:
        description: The shasum of the Vagrant RubyGem or commit
        required: true
        type: string
    outputs:
      deb-packages-id:
        description: Cache identifier for deb packages
        value: ${{ jobs.info.outputs.deb-packages-id }}
jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      deb-32-substrate-id: ${{ steps.inspect.outputs.deb-32-substrate-id }}
      deb-32-substrate-exists: ${{ steps.inspect.outputs.deb-32-substrate-exists }}
      deb-32-install-id: ${{ steps.inspect.outputs.deb-32-install-id }}
      deb-32-install-exists: ${{ steps.inspect.outputs.deb-32-install-exists }}
      deb-64-substrate-id: ${{ steps.inspect.outputs.deb-64-substrate-id }}
      deb-64-substrate-exists: ${{ steps.inspect.outputs.deb-64-substrate-exists }}
      deb-64-install-id: ${{ steps.inspect.outputs.deb-64-install-id }}
      deb-64-install-exists: ${{ steps.inspect.outputs.deb-64-install-exists }}
      deb-packages-id: ${{ steps.inspect.outputs.deb-packages-id }}
      deb-packages-exists: ${{ steps.inspect.outputs.deb-packages-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Gather information
        id: inspect
        run: ./.ci/deb-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ inputs.vagrant-shasum }}
  build-substrate-32:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-32-substrate-exists != 'true' }}
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: go.mod
      - name: Build Launchers
        run: make bin/launcher/linux-386
      - name: Build Substrate 32-bit
        run: sudo ./.ci/ubuntu-substrate 32 ./artifacts
      - name: Cache Substrate 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # The 64 bit substrate is also used by appimage so it was
  # extracted to an isolated workflow to be shared
  build-substrate-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    needs: [info]
    permissions:
      contents: write
    uses: ./.github/workflows/build-deb-substrate64.yml
    with:
      deb-64-substrate-id: ${{ needs.info.outputs.deb-64-substrate-id }}
    secrets: inherit
  build-install-32:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-32-install-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-32]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Vagrant Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ inputs.vagrant-artifacts-name }}
          path: ${{ inputs.vagrant-artifacts-path }}
      - name: Run install
        run: sudo ./.ci/ubuntu-install "${ARTIFACTS_PATH}" ./substrates ./artifacts
        env:
          ARTIFACTS_PATH: ${{ inputs.vagrant-artifacts-path }}
      - name: Cache Install 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-install-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-install-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Vagrant RubyGem
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ inputs.vagrant-gem-name }}
          path: ${{ inputs.vagrant-gem-path }}
      - name: Run install
        run: sudo ./.ci/ubuntu-install "${VAGRANT_GEM_PATH}" ./substrates ./artifacts
        env:
          VAGRANT_GEM_PATH: ${{ inputs.vagrant-gem-path }}
      - name: Cache Install 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-packages:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-packages-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-install-32, build-install-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Fetch Install 32-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Install 64-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: 3.1
      - name: Install fpm
        run: gem install --no-document fpm
      - name: Fetch Vagrant Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ inputs.vagrant-artifacts-name }}
          path: ${{ inputs.vagrant-artifacts-path }}
      - name: Package 32-bit
        run: ./package/build-deb ./artifacts/installed_ubuntu_386.zip "${ARTIFACTS_PATH}/vagrant-go_linux_386" ./pkgs "${VERSION}"
        env:
          ARTIFACTS_PATH: ${{ inputs.vagrant-artifacts-path }}
          VERSION: ${{ inputs.vagrant-version }}
      - name: Package 64-bit
        run: ./package/build-deb ./artifacts/installed_ubuntu_x86_64.zip "${ARTIFACTS_PATH}/vagrant-go_linux_amd64" ./pkgs "${VERSION}"
        env:
          ARTIFACTS_PATH: ${{ inputs.vagrant-artifacts-path }}
          VERSION: ${{ inputs.vagrant-version }}
      - name: Cache Vagrant debs
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
