on:
  workflow_call:
    inputs:
      vagrant_draft_name:
        description: Name of the Vagrant repository draft release containing gem for build
        required: false
        type: string
      vagrant_release_name:
        description: Name of the Vagrant repository release containing gem for build
        required: false
        type: string
    outputs:
      deb-packages-id:
        description: Cache identifier for deb packages
        value: ${{ jobs.info.outputs.deb-packages-id }}
      vagrant-version:
        description: Version of Vagrant package built
        value: ${{ jobs.info.outputs.vagrant-version }}

jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      vagrant-version: ${{ steps.vagrant-gem.outputs.vagrant-version }}
      vagrant-shasum: ${{ steps.vagrant-gem.outputs.vagrant-shasum }}
      deb-32-substrate-id: ${{ steps.inspect.outputs.deb-32-substrate-id }}
      deb-32-substrate-exists: ${{ steps.inspect.outputs.deb-32-substrate-exists }}
      deb-32-install-id: ${{ steps.inspect.outputs.deb-32-install-id }}
      deb-32-install-exists: ${{ steps.inspect.outputs.deb-32-install-exists }}
      deb-64-substrate-id: ${{ steps.inspect.outputs.deb-64-substrate-id }}
      deb-64-substrate-exists: ${{ steps.inspect.outputs.deb-64-substrate-exists }}
      deb-64-install-id: ${{ steps.inspect.outputs.deb-64-install-id }}
      deb-64-install-exists: ${{ steps.inspect.outputs.deb-64-install-exists }}
      deb-packages-id: ${{ steps.inspect.outputs.deb-packages-id }}
      deb-packages-exists: ${{ steps.inspect.outputs.deb-packages-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        if: needs.info.outputs.unsigned-cache-exists != 'true'
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install Ruby
        run: sudo apt-get install -yq ruby
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Fetch Vagrant RubyGem
        id: vagrant-gem
        run: ./.ci/fetch-vagrant-rubygem
        env:
          VAGRANT_DRAFT_NAME: ${{ inputs.draft_name }}
          VAGRANT_RELEASE_NAME: ${{ inputs.release_name }}
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.vagrant_token }}
      - name: Gather information
        id: inspect
        run: ./.ci/deb-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ steps.vagrant-gem.outputs.vagrant-shasum }}
      - name: Store Vagrant RubyGem
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-rubygem
          path: ./gem
      - name: Build launchers
        run: make bin/launcher/linux
      - name: Store Launchers
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-launchers
          path: ./bin
  build-substrate-32:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-32-substrate-exists != 'true' }}
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Launchers
        uses: actions/download-artifact@v3
        with:
          name: vagrant-launchers
          path: ./bin
      - name: Build Substrate 32-bit
        run: sudo -E ./.ci/ubuntu-substate 32 ./artifacts
      - name: Cache Substrate 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-substrate-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Launchers
        uses: actions/download-artifact@v3
        with:
          name: vagrant-launchers
          path: ./bin
      - name: Build Substrate 64-bit
        run: sudo -E ./.ci/ubuntu-substate 64 ./artifacts
      - name: Cache Substrate 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-install-32:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-32-install-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-32]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-substrate-id }}
      - name: Fetch RubyGem
        uses: actions/download-artifact@v3
        with:
          name: vagrant-rubygem
          path: ./gem
      - name: Run install
        run: ./.ci/ubuntu-install ./gem ./substrates ./artifacts
      - name: Cache Install 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-install-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-install-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
      - name: Fetch RubyGem
        uses: actions/download-artifact@v3
        with:
          name: vagrant-rubygem
          path: ./gem
      - name: Run install
        run: ./.ci/ubuntu-install ./gem ./substrates ./artifacts
      - name: Cache Install 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-packages:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-packages-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-install-32, build-install-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Install 32-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-32-install-id }}
      - name: Fetch Install 64-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-install-id }}
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
      - name: Install fpm
        run: gem install --no-document fpm
      - name: Package 32-bit
        run: ./package/build-deb ./artifacts/installed_vagrant_386.zip ./pkgs "${VERSION}"
        env:
          VERSION: ${{ needs.info.outputs.vagrant-version }}
      - name: Package 64-bit
        run: ./package/build-deb ./artifacts/installed_vagrant_x86_64.zip ./pkgs "${VERSION}"
        env:
          VERSION: ${{ needs.info.outputs.vagrant-version }}
      - name: Cache Vagrant debs
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
