on:
  workflow_call:
    inputs:
      deb-64-substrate-id:
        description: Cache identifier for substrate artifact
        required: true
        type: string

# Since this workflow is used in multiple locations
# only allow one of them to run at a time to prevent
# them attempting to run on top of eachother
concurrency: ${{ github.workflow }}

jobs:
  info:
    name: Check Substrate Exists
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      deb-64-substrate-exists: ${{ steps.exists.outputs.substrate-exists }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Substrate Check
        id: exists
        run: |
          . ./.ci/load-ci.sh
          if github_draft_release_exists "${repo_name}" "${SUBSTRATE_ID}"; then
            printf "deb-64-substrate-exists=true\n" >> "${GITHUB_OUTPUT}"
          fi
        env:
          SUBSTRATE_ID: ${{ inputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-substrate-64:
    name: Build Debian 64 Substrate
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    runs-on: ubuntu-latest
    needs: [info]
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build Launchers
        run: make bin/launcher/linux-x86_64
      - name: Build Substrate 64-bit
        run: sudo ./.ci/ubuntu-substrate 64 ./artifacts
      - name: Cache Substrate 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ inputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
