name: Vagrant RPM Builder
on:
  workflow_call:
    inputs:
      vagrant-artifacts-name:
        description: Name of upload containing Vagrant build artifacts
        required: true
        type: string
      vagrant-artifacts-path:
        description: Path used for Vagrant build artifacts
        required: true
        type: string
      vagrant-gem-name:
        description: Name of upload containing the Vagrant RubyGem
        required: true
        type: string
      vagrant-gem-path:
        description: Path used for the Vagrant RubyGem (directory)
        required: true
        type: string
      vagrant-version:
        description: Version of Vagrant being built
        required: true
        type: string
      vagrant-shasum:
        description: The shasum of the Vagrant RubyGem or commit
        required: true
        type: string
    outputs:
      rpm-packages-id:
        description: Cache identifier for rpm packages
        value: ${{ jobs.info.outputs.rpm-packages-id }}
jobs:
  info:
    if: github.repository == 'hashicorp/vagrant-builders'
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      rpm-32-substrate-id: ${{ steps.inspect.outputs.rpm-32-substrate-id }}
      rpm-32-substrate-exists: ${{ steps.inspect.outputs.rpm-32-substrate-exists }}
      rpm-32-install-id: ${{ steps.inspect.outputs.rpm-32-install-id }}
      rpm-32-install-exists: ${{ steps.inspect.outputs.rpm-32-install-exists }}
      rpm-64-substrate-id: ${{ steps.inspect.outputs.rpm-64-substrate-id }}
      rpm-64-substrate-exists: ${{ steps.inspect.outputs.rpm-64-substrate-exists }}
      rpm-64-install-id: ${{ steps.inspect.outputs.rpm-64-install-id }}
      rpm-64-install-exists: ${{ steps.inspect.outputs.rpm-64-install-exists }}
      rpm-packages-id: ${{ steps.inspect.outputs.rpm-packages-id }}
      rpm-packages-exists: ${{ steps.inspect.outputs.rpm-packages-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Gather information
        id: inspect
        run: ./.ci/rpm-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ inputs.vagrant-shasum }}
  build-substrate-32:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.rpm-32-substrate-exists != 'true'
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
      - name: Build Launchers
        run: make bin/launcher/linux-386
      - name: Build Substrate 32-bit
        run: sudo ./.ci/centos-substrate 32 ./artifacts
      - name: Cache Substrate 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-32-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-substrate-64:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.rpm-64-substrate-exists != 'true'
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
      - name: Build Launchers
        run: make bin/launcher/linux-x86_64
      - name: Build Substrate 64-bit
        run: sudo ./.ci/centos-substrate 64 ./artifacts
      - name: Cache Substrate 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-install-32:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.rpm-32-install-exists != 'true' && !cancelled() && !failure()
    needs: [info, build-substrate-32]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-32-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Vagrant RubyGem
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ${{ inputs.vagrant-gem-name }}
          path: ${{ inputs.vagrant-gem-path }}
      - name: Run install
        run: sudo ./.ci/centos-install "${VAGRANT_GEM_PATH}" ./substrates ./artifacts
        env:
          VAGRANT_GEM_PATH: ${{ inputs.vagrant-gem-path }}
      - name: Cache Install 32-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-32-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-install-64:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.rpm-64-install-exists != 'true' && !cancelled() && !failure()
    needs: [info, build-substrate-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Vagrant RubyGem
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ${{ inputs.vagrant-gem-name }}
          path: ${{ inputs.vagrant-gem-path }}
      - name: Run install
        run: sudo ./.ci/centos-install "${VAGRANT_GEM_PATH}" ./substrates ./artifacts
        env:
          VAGRANT_GEM_PATH: ${{ inputs.vagrant-gem-path }}
      - name: Cache Install 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-64-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-packages:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.rpm-packages-exists != 'true' && !cancelled() && !failure()
    needs: [info, build-install-32, build-install-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Fetch Install 32-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-32-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Install 64-bit
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-64-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Ruby
        uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # v1.180.1
        with:
          ruby-version: 3.1
      - name: Install fpm
        run: gem install --no-document fpm
      - name: Fetch Vagrant Artifacts
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ${{ inputs.vagrant-artifacts-name }}
          path: ${{ inputs.vagrant-artifacts-path }}
      - name: Package 32-bit
        run: ./package/build-rpm ./artifacts/installed_centos_386.zip ./pkgs "${VERSION}"
        env:
          VAGRANT_ARTIFACTS: ${{ inputs.vagrant-artifacts-path }}
          VERSION: ${{ inputs.vagrant-version }}
      - name: Package 64-bit
        run: ./package/build-rpm ./artifacts/installed_centos_x86_64.zip ./pkgs "${VERSION}"
        env:
          VAGRANT_ARTIFACTS: ${{ inputs.vagrant-artifacts-path }}
          VERSION: ${{ inputs.vagrant-version }}
      - name: Cache Vagrant rpms
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.rpm-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
