on:
  workflow_call:
    inputs:
      vagrant_draft_name:
        description: Name of the Vagrant repository draft release containing gem for build
        required: false
        type: string
      vagrant_release_name:
        description: Name of the Vagrant repository release containing gem for build
        required: false
        type: string
    outputs:
      appimage-package-id:
        description: Cache identifier for appimage packages
        value: ${{ jobs.info.outputs.appimage-package-id }}
      vagrant-version:
        description: Version of Vagrant package built
        value: ${{ jobs.info.outputs.vagrant-version }}

jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      vagrant-version: ${{ steps.vagrant-artifacts.outputs.vagrant-version }}
      vagrant-shasum: ${{ steps.vagrant-artifacts.outputs.vagrant-shasum }}
      deb-64-substrate-id: ${{ steps.inspect.outputs.deb-64-substrate-id }}
      deb-64-substrate-exists: ${{ steps.inspect.outputs.deb-64-substrate-exists }}
      appimage-package-id: ${{ steps.inspect.outputs.appimage-package-id }}
      appimage-package-exists: ${{ steps.inspect.outputs.appimage-package-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -yq ruby
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Fetch Vagrant RubyGem
        id: vagrant-artifacts
        run: ./.ci/fetch-vagrant-files
        env:
          VAGRANT_DRAFT_NAME: ${{ inputs.draft_name }}
          VAGRANT_RELEASE_NAME: ${{ inputs.release_name }}
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.vagrant_token }}
      - name: Gather information
        id: inspect
        run: ./.ci/deb-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ steps.vagrant-gem.outputs.vagrant-shasum }}
      - name: Store Vagrant RubyGem
        if: ${{ steps.inspect.outputs.appimage-package-exists != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-rubygem-appimage
          path: ./gem
  build-substrate-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    needs: [info]
    permissions:
      contents: write
    uses: ./.github/workflows/build-deb-substrate64.yml
    secrets: inherit
  build-package:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.appimage-package-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch RubyGem
        uses: actions/download-artifact@v3
        with:
          name: vagrant-rubygem-appimage
          path: ./gem
      - name: Package appimage
        run: sudo ./.ci/build-appimage-in-chroot ./gem ./substrates ./pkgs
      - name: Cache Vagrant appimage
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.appimage-package-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
