on:
  workflow_call:
    outputs:
      substrate-id:
        description: Cache identifier for deb 64 substrate
        value: ${{ jobs.info.outputs.deb-64-substrate-id }}

# Since this workflow is used in multiple locations
# only allow one of them to run at a time to prevent
# them attempting to run on top of eachother
concurrency: ${{ github.workflow }}

jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      deb-64-substrate-id: ${{ steps.inspect.outputs.deb-64-substrate-id }}
      deb-64-substrate-exists: ${{ steps.inspect.outputs.deb-64-substrate-exists }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Build launchers
        run: make bin/launcher/linux-x86_64
      - name: Store Launchers
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: vagrant-launchers
          path: ./bin
      - name: Gather information
        id: inspect
        run: ./.ci/deb-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-substrate-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Fetch Launchers
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: vagrant-launchers
          path: ./bin
      - name: Build Substrate 64-bit
        run: sudo ./.ci/ubuntu-substrate 64 ./artifacts
      - name: Cache Substrate 64-bit
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
