name: Vagrant AppImage Builder
on:
  workflow_call:
    inputs:
      vagrant-artifacts-name:
        description: Name of upload containing Vagrant build artifacts
        required: true
        type: string
      vagrant-artifacts-path:
        description: Path used for Vagrant build artifacts
        required: true
        type: string
      vagrant-gem-name:
        description: Name of upload containing the Vagrant RubyGem
        required: true
        type: string
      vagrant-gem-path:
        description: Path used for the Vagrant RubyGem (directory)
        required: true
        type: string
      vagrant-version:
        description: Version of Vagrant being built
        required: true
        type: string
      vagrant-shasum:
        description: The shasum of the Vagrant RubyGem or commit
        required: true
        type: string
    outputs:
      appimage-package-id:
        description: Cache identifier for appimage packages
        value: ${{ jobs.info.outputs.appimage-package-id }}
jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      deb-64-substrate-id: ${{ steps.inspect.outputs.deb-64-substrate-id }}
      deb-64-substrate-exists: ${{ steps.inspect.outputs.deb-64-substrate-exists }}
      appimage-package-id: ${{ steps.inspect.outputs.appimage-package-id }}
      appimage-package-exists: ${{ steps.inspect.outputs.appimage-package-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Gather information
        id: inspect
        run: ./.ci/deb-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ inputs.vagrant-shasum }}
  build-substrate-64:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.deb-64-substrate-exists != 'true' }}
    needs: [info]
    permissions:
      contents: write
    uses: ./.github/workflows/build-deb-substrate64.yml
    with:
      deb-64-substrate-id: ${{ needs.info.outputs.deb-64-substrate-id }}
    secrets: inherit
  build-package:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.appimage-package-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate-64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.deb-64-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Vagrant RubyGem
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.vagrant-gem-name }}
          path: ${{ inputs.vagrant-gem-path }}
      - name: Package appimage
        run: sudo ./.ci/build-appimage-in-chroot "${VAGRANT_GEM_PATH}" ./substrates ./pkgs
        env:
          VAGRANT_GEM_PATH: ${{ inputs.vagrant-gem-path }}
      - name: Cache Vagrant appimage
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.appimage-package-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
