on:
  workflow_call:
    inputs:
      vagrant_draft_name:
        description: Name of the Vagrant repository draft release containing gem for build
        required: false
        type: string
      vagrant_release_name:
        description: Name of the Vagrant repository release containing gem for build
        required: false
        type: string
    outputs:
      arch-package-id:
        description: Cache identifier for arch linux package
        value: ${{ jobs.info.outputs.arch-package-id }}
      vagrant-version:
        description: Version of Vagrant package built
        value: ${{ jobs.info.outputs.vagrant-version }}
      vagrant-commit-id:
        description: Commit ID on the Vagrant repository associated to this build
        value: ${{ jobs.info.outputs.vagrant-commit-id }}

jobs:
  info:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' }}
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    outputs:
      vagrant-version: ${{ steps.vagrant-artifacts.outputs.vagrant-version }}
      vagrant-shasum: ${{ steps.vagrant-artifacts.outputs.vagrant-shasum }}
      vagrant-commit-id: ${{ steps.vagrant-artifacts.vagrant-commit-id }}
      arch-substrate-id: ${{ steps.inspect.outputs.arch-substrate-id }}
      arch-substrate-exists: ${{ steps.inspect.outputs.arch-substrate-exists }}
      arch-install-id: ${{ steps.inspect.outputs.arch-install-id }}
      arch-install-exists: ${{ steps.inspect.outputs.arch-install-exists }}
      arch-package-id: ${{ steps.inspect.outputs.arch-package-id }}
      arch-package-exists: ${{ steps.inspect.outputs.arch-package-exists }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        if: ${{ steps.inspect.outputs.arch-substrate-exists != 'true' }}
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -yq ruby
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Fetch Vagrant Artifacts
        id: vagrant-artifacts
        run: ./.ci/fetch-vagrant-files
        env:
          VAGRANT_DRAFT_NAME: ${{ inputs.draft_name }}
          VAGRANT_RELEASE_NAME: ${{ inputs.release_name }}
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.vagrant_token }}
      - name: Gather information
        id: inspect
        run: ./.ci/arch-build-information
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_SHASUM: ${{ steps.vagrant-gem.outputs.vagrant-shasum }}
      - name: Store Vagrant RubyGem
        if: ${{ steps.inspect.outputs.arch-install-exists != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-rubygem
          path: ./gem
      - name: Store Vagrant Artifacts
        if: ${{ steps.inspect.outputs.arch-package-exists != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-artifacts
          path: ./vagrant-artifacts
      - name: Build launchers
        if: ${{ steps.inspect.outputs.arch-substrate-exists != 'true' }}
        run: make bin/launcher/linux-x86_64
      - name: Store Launchers
        if: ${{ steps.inspect.outputs.arch-substrate-exists != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: vagrant-launchers-arch
          path: ./bin
  build-substrate:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.arch-substrate-exists != 'true' }}
    needs: [info]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Launchers
        uses: actions/download-artifact@v3
        with:
          name: vagrant-launchers-arch
          path: ./bin
      - name: Enable LXD
        run: sudo usermod -a -G lxd "${USER}"
      - name: Build Substrate
        run: sg lxd "./.ci/arch-substrate ./substrates"
      - name: Cache Substrate
        run: ./.ci/create-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.arch-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  install-vagrant:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.arch-install-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, build-substrate]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Substrate
        run: ./.ci/restore-cache "${CACHE_ID}" ./substrates
        env:
          CACHE_ID: ${{ needs.info.outputs.arch-substrate-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch vagrant gem
        uses: actions/download-artifact@v3
        with:
          name: vagrant-rubygem
          path: ./gem
      - name: Enable LXD
        run: sudo usermod -a -G lxd "${USER}"
      - name: Install Vagrant
        run: sg lxd "./.ci/arch-install ./gem ./substrates ./artifacts"
      - name: Cache Install
        run: ./.ci/create-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.arch-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-packages:
    if: ${{ github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.arch-package-exists != 'true' && !cancelled() && !failure() }}
    needs: [info, install-vagrant]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch Install
        run: ./.ci/restore-cache "${CACHE_ID}" ./artifacts
        env:
          CACHE_ID: ${{ needs.info.outputs.arch-install-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Artifacts
        uses: actions/download-artifact@v3
        with:
          name: vagrant-artifacts
          path: ./vagrant-artifacts
      - name: Enable LXD
        run: sudo usermod -a -G lxd "${USER}"
      - name: Build package
        run: sg lxd "./.ci/arch-package ./artifacts/vagrant-installed.zip ./vagrant-artifacts/vagrant-go_linux_amd64 ./pkgs ${VERSION}"
        env:
          VERSION: ${{ needs.info.outputs.vagrant-version }}
      - name: Cache Package
        run: ./.ci/create-cache "${CACHE_ID}" ./pkgs
        env:
          CACHE_ID: ${{ needs.info.outputs.arch-package-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
