on:
  push:
    branches:
      - 'build-rpms-*'

jobs:
  build-rpm-packages:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Build rpm packages
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-rpms.yml
    secrets: inherit
  publish:
    if: github.repository == 'hashicorp/vagrant-builders'
    needs: [build-rpm-packages]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Fetch rpm packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-rpm-packages.outputs.rpm-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create prerelease
        run: . .ci/load-ci.sh && prerelease "${VAGRANT_VERSION}" ./pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VAGRANT_VERSION: ${{ needs.build-rpm-packages.outputs.vagrant-version }}
