name: Release Notifier
on:
  workflow_run:
    workflows:
      - Vagrant HashiCorp Release
    types:
      - completed

jobs:
  released:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/slack webhook;
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Send Notification
        run: |
          . .ci/load-ci.sh || exit
          slack -m "$(printf "<%s|Vagrant release process> has completed successfully 🎉\n\nUpdate <https://checkpoint.hashicorp.com/control|checkpoint> to finalize release." "${WORKFLOW_URL")"
        env:
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.webhook }}
          SLACK_CHANNEL: '#team-vagrant'
          SLACK_USERNAME: Release Notification
          SLACK_TITLE: Vagrant Release Process
          SLACK_STATE: success
          WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
  failed:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/slack webhook;
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Send Notification
        run: |
          . .ci/load-ci.sh || exit
          slack -m "$(printf "<%s|Vagrant release process> has failed" "${WORKFLOW_URL}")"
        env:
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.webhook }}
          SLACK_CHANNEL: '#team-vagrant'
          SLACK_TITLE: '⚠️ Vagrant Release Process⚠️'
          SLACK_USERNAME: Vagrant Release Builder
          SLACK_STATE: error
          WORKFLOW_URL: ${{ github.event.workflow_run.html_url }}
