name: Packaging Vars

on:
  workflow_call:
    outputs:
      ASSETS_PASSWORD:
        value: ${{ jobs.get-vars.outputs.ASSETS_PASSWORD }}
      MACOS_NOTARIZE_USERNAME:
        value: ${{ jobs.get-vars.outputs.MACOS_NOTARIZE_USERNAME }}
      MACOS_NOTARIZE_PASSWORD:
        value: ${{ jobs.get-vars.outputs.MACOS_NOTARIZE_PASSWORD }}
      MACOS_SIGN_PASSWORD:
        value: ${{ jobs.get-vars.outputs.MACOS_SIGN_PASSWORD }}
      WINDOWS_SIGN_PASSWORD:
        value: ${{ jobs.get-vars.outputs.WINDOWS_SIGN_PASSWORD }}
      SIGNORE_CLIENT_ID:
        value: ${{ jobs.get-vars.outputs.SIGNORE_CLIENT_ID }}
      SIGNORE_CLIENT_SECRET:
        value: ${{ jobs.get-vars.outputs.SIGNORE_CLIENT_SECRET }}
      SIGNORE_SIGNER:
        value: ${{ jobs.get-vars.outputs.SIGNORE_SIGNER }}
      MACOS_PACKAGE_CERT_CONTENT:
        value: ${{ jobs.get-vars.outputs.MACOS_PACKAGE_CERT_CONTENT }}
      MACOS_PACKAGE_KEY_CONTENT:
        value: ${{ jobs.get-vars.outputs.MACOS_PACKAGE_KEY_CONTENT }}
      MACOS_CODE_CERT_CONTENT:
        value: ${{ jobs.get-vars.outputs.MACOS_CODE_CERT_CONTENT }}
      WIN_SIGNING_KEY:
        value: ${{ jobs.get-vars.outputs.WIN_SIGNING_KEY }}
      PACKAGE_NOTIFICATION_SNS_TOPIC_ARN:
        value: ${{ jobs.get-vars.outputs.PACKAGE_NOTIFICATION_SNS_TOPIC_ARN }}


jobs:
  get-vars:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    outputs:
      ASSETS_PASSWORD: ${{ steps.vars.outputs.ASSETS_PASSWORD }}
      MACOS_NOTARIZE_USERNAME: ${{ steps.vars.outputs.MACOS_NOTARIZE_USERNAME }}
      MACOS_NOTARIZE_PASSWORD: ${{ steps.vars.outputs.MACOS_NOTARIZE_PASSWORD }}
      MACOS_SIGN_PASSWORD: ${{ steps.vars.outputs.MACOS_SIGN_PASSWORD }}
      WINDOWS_SIGN_PASSWORD: ${{ steps.vars.outputs.WINDOWS_SIGN_PASSWORD }}
      SIGNORE_CLIENT_ID: ${{ steps.vars.outputs.SIGNORE_CLIENT_ID }}
      SIGNORE_CLIENT_SECRET: ${{ steps.vars.outputs.SIGNORE_CLIENT_SECRET }}
      SIGNORE_SIGNER: ${{ steps.vars.outputs.SIGNORE_SIGNER }}
      MACOS_PACKAGE_CERT_CONTENT: ${{ steps.vars.outputs.MACOS_PACKAGE_CERT_CONTENT }}
      MACOS_PACKAGE_KEY_CONTENT: ${{ steps.vars.outputs.MACOS_PACKAGE_KEY_CONTENT }}
      MACOS_CODE_CERT_CONTENT: ${{ steps.vars.outputs.MACOS_CODE_CERT_CONTENT }}
      WIN_SIGNING_KEY_CONTENT: ${{ steps.vars.outputs.WIN_SIGNING_KEY_CONTENT }}
      PACKAGE_NOTIFICATION_SNS_TOPIC_ARN: ${{ steps.vars.outputs.PACKAGE_NOTIFICATION_SNS_TOPIC_ARN }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Fetch vars
        id: vars
        uses: hashicorp/vault-action@2.2.0
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificates: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/${{ github.repository }} asset_password | ASSET_PASSWORD;
            kv/data/github/${{ github.repository }} macos_notarize_username | MACOS_NOTARIZE_USERNAME;
            kv/data/github/${{ github.repository }} macos_notarize_password | MACOS_NOTARIZE_PASSWORD;
            kv/data/github/${{ github.repository }} macos_sign_password | MACOS_SIGN_PASSWORD;
            kv/data/github/${{ github.repository }} windows_sign_password | WINDOWS_SIGN_PASSWORD;
            kv/data/github/${{ github.repository }} signore_client_id | SIGNORE_CLIENT_ID;
            kv/data/github/${{ github.repository }} signore_client_secret | SIGNORE_CLIENT_SECRET;
            kv/data/github/${{ github.repository }} signore_signer | SIGNORE_SIGNER;
            kv/data/github/${{ github.repository }} macos_package_cert_content | MACOS_PACKAGE_CERT_CONTENT;
            kv/data/github/${{ github.repository }} macos_package_key_content | MACOS_PACKAGE_KEY_CONTENT;
            kv/data/github/${{ github.repository }} macos_code_cert_content | MACOS_CODE_CERT_CONTENT;
            kv/data/github/${{ github.repository }} win_signing_key_content | WIN_SIGNING_KEY_CONTENT;
            kv/data/github/${{ github.repository }} package_notification_sns_topic_arn | PACKAGE_NOTIFICATION_SNS_TOPIC_ARN;
