on:
  schedule:
    - cron: '12 5 * * *'
  workflow_dispatch:

jobs:
  prune-drafts:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Prune stale draft releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Prune
        id: prune
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ./.ci/.ci-utility-files/common.sh

          # Prune draft releases over 2 days old
          github_draft_release_prune "2"
