on:
  schedule:
    - cron: '12 5 * * *'
  workflow_dispatch:

jobs:
  prune-drafts:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Prune stale draft releases
    runs-on: ubuntu-latest
    permisions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Prune
        id: prune
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . ./.ci/.ci-utility-files/common.sh

          # Prune draft releases over 20 days old
          github_draft_release_prune "20"
