on:
  push:
    tags: 'v*'

jobs:
  info:
    if: github.repository == 'hashicorp/vagrant-builders'
    name: Generate info
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      contents: write
      id-token: write
    outputs:
      vagrant-version: ${{ steps.vagrant-info.outputs.vagrant-version }}
      vagrant-shasum: ${{ steps.vagrant-info.outputs.vagrant-shasum }}
      vagrant-commit-id: ${{ steps.vagrant-info.outputs.vagrant-commit-id }}
      vagrant-tag: ${{ steps.vagrant-info.outputs.vagrant-tag }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -yq ruby
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Fetch Vagrant Info
        id: vagrant-info
        run: ./.ci/fetch-vagrant-info --tag-required
        env:
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.vagrant_token }}
  build-appimage-package:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build appimage package
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-appimage.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  build-archlinux-package:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build Arch Linux Package
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-arch.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  build-deb-packages:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build deb packages
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-debs.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  build-macos-package:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build macOS package
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-macos.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  build-rpm-packages:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build rpm packages
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-rpms.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  build-windows-packages:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Build Windows Packages
    needs: [info]
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/build-windows.yml
    with:
      vagrant_release_name: ${{ needs.info.outputs.vagrant-tag }}
    secrets: inherit
  release:
    if: github.repository == 'hashicorp/vagrant-builders' && needs.info.outputs.release-exists != 'true'
    name: Release
    needs: [info, build-appimage-package, build-archlinux-package, build-deb-packages, build-macos-package, build-rpm-packages, build-windows-packages]
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/teams/vagrant/hashibot vagrant_token;
            kv/data/teams/vagrant/hashibot signore_token;
            kv/data/github/hashicorp/vagrant-builders signore_client_id;
            kv/data/github/hashicorp/vagrant-builders signore_client_secret;
            kv/data/github/hashicorp/vagrant-builders signore_gpg_signer;
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Fetch appimage package
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-appimage-package.outputs.appimage-package-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Arch Linux package
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-archlinux-package.outputs.arch-package-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch deb packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-deb-packages.outputs.deb-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch macOS DMG
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-macos-package.outputs.dmg-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch rpm packages
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-rpm-packages.outputs.rpm-packages-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch 32 Bit Windows Package
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-windows-packages.outputs.msi-32-signed-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch 64 Bit Windows Package
        run: ./.ci/restore-cache "${CACHE_ID}" ./pkg
        env:
          CACHE_ID: ${{ needs.build-windows-packages.outputs.msi-64-signed-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update macOS package name
        run: ./.ci/macos-rename-release ./pkg
      - name: Validate package list
        run: ./.ci/validate-package-list ./pkg
      - name: Release Packages
        run: ./.ci/publish-release "${VAGRANT_VERSION}" ./pkg
        env:
          HASHIBOT_TOKEN: ${{ steps.secrets.outputs.hashicorp_release_github_token }}
          VAGRANT_VERSION: ${{ needs.info.outputs.vagrant-version }}
          SIGNORE_SIGNER: ${{ steps.secrets.outputs.signore_gpg_signer }}
          SIGNORE_CLIENT_ID: ${{ steps.secrets.outputs.signore_client_id  }}
          SIGNORE_CLIENT_SECRET: ${{ steps.secrets.outputs.signore_client_secret }}
          RELEASE_AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.releases_aws_access_key_id }}
          RELEASE_AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.releases_aws_secret_access_key }}
          RELEASE_AWS_ASSUME_ROLE_ARN: ${{ steps.secrets.outputs.releases_aws_role_arn }}
          HC_RELEASES_PROD_SNS_TOPIC: ${{ vars.HASHICORP_RELEASES_SNS_ARN }}
          HC_RELEASES_PROD_HOST: ${{ steps.secrets.outputs.releases_api_production_host }}
          HC_RELEASES_PROD_KEY: ${{ steps.secrets.outputs.releases_api_production_key }}
          HC_RELEASES_STAGING_HOST: ${{ steps.secrets.outputs.releases_api_staging_host }}
          HC_RELEASES_STAGING_KEY: ${{ steps.secrets.outputs.releases_api_staging_key }}
          HASHICORP_PUBLIC_GPG_KEY_ID: ${{ vars.HASHICORP_GPG_SIGNING_ID }}
