name: Slack Vars

on:
  workflow_call:
    outputs:
      SLACK_WEBHOOK:
        value: ${{ jobs.get-vars.outputs.SLACK_WEBHOOK }}

jobs:
  get-vars:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    outputs:
      SLACK_WEBHOOK: ${{ steps.vars.outputs.SLACK_WEBHOOK }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Fetch vars
        id: vars
        uses: hashicorp/vault-action@2.2.0
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificates: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/${{ github.repository }} slack_webhook | SLACK_WEBHOOK;
