name: Vagrant Artifact Builder
on:
  workflow_call:
    inputs:
      vagrant-commit-id:
        description: Vagrant repository commit ID
        required: false
        type: string
    outputs:
      artifacts-name:
        description: Artifact name for Vagrant build artifacts
        value: ${{ jobs.build.outputs.artifacts-name }}
      artifacts-path:
        description: Artifact path for Vagrant build artifacts
        value: ${{ jobs.build.outputs.artifacts-path }}
      gem-name:
        description: Artifact name for Vagrant RubyGem build artifact
        value: ${{ jobs.build.outputs.gem-name }}
      gem-path:
        description: Artifact path for Vagrant RubyGem build artifact
        value: ${{ jobs.build.outputs.gem-path }}
      licenses-name:
        description: Artifact name for Vagrant packaging licenses artifact
        value: ${{ jobs.build.outputs.licenses-name }}
      licenses-path:
        description: Artifact path for Vagrant packaging licenses artifact
        value: ${{ jobs.build.outputs.licenses-path }}
      vagrant-shasum:
        description: SHASUM value used for Vagrant source identification
        value: ${{ jobs.build.outputs.vagrant-shasum }}
      vagrant-version:
        description: Version of Vagrant being built
        value: ${{ jobs.build.outputs.vagrant-version }}
      vagrant-commit-id:
        description: The commit ID (sha) for the Vagrant source being built
        value: ${{ jobs.build.outputs.vagrant-commit-id }}
      vagrant-short-commit-id:
        description: The short commit ID (sha) for the Vagrant source being built
        value: ${{ jobs.build.outputs.vagrant-short-commit-id }}


jobs:
  build:
    name: Build Vagrant Artifacts
    if: github.repository == 'hashicorp/vagrant-builders'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      artifacts-name: ${{ steps.names.outputs.artifacts-name }}
      artifacts-path: ${{ steps.names.outputs.artifacts-path }}
      gem-name: ${{ steps.names.outputs.gem-name }}
      gem-path: ${{ steps.names.outputs.gem-path }}
      licenses-name: ${{ steps.names.outputs.licenses-name }}
      licenses-path: ${{ steps.names.outputs.licenses-path }}
      vagrant-shasum: ${{ steps.info.outputs.vagrant-shasum }}
      vagrant-version: ${{ steps.info.outputs.vagrant-version }}
      vagrant-commit-id: ${{ steps.commit.outputs.vagrant-commit-id }}
      vagrant-short-commit-id: ${{ steps.commit.outputs.vagrant-short-commit-id }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set Names and Paths
        id: names
        run: |
          printf "artifacts-name=vagrant-build-artifacts\n" >> "${GITHUB_OUTPUT}"
          printf "artifacts-path=./vagrant-build-artifacts\n" >> "${GITHUB_OUTPUT}"
          printf "gem-name=vagrant-build-rubygem\n" >> "${GITHUB_OUTPUT}"
          printf "gem-path=./gem\n" >> "${GITHUB_OUTPUT}"
          printf "licenses-name=vagrant-licenses\n" >> "${GITHUB_OUTPUT}"
          printf "licenses-path=./generated-licenses\n" >> "${GITHUB_OUTPUT}"
      - name: Code Checkout Main
        if: inputs.vagrant-commit-id == ''
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: hashicorp/vagrant
          ref: main
          path: ./vagrant-source
      - name: Code Checkout
        if: inputs.vagrant-commit-id != ''
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: hashicorp/vagrant
          ref: ${{ inputs.vagrant-commit-id }}
          path: ./vagrant-source
      - name: Vagrant Commit ID
        id: commit
        run: ./.ci/fetch-vagrant-source-info ./vagrant-source
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Cached Vagrant Artifacts
        if: steps.commit.outputs.vagrant-cache-exists == 'true'
        run: ./.ci/restore-cache "${CACHE_ID}" "${VAGRANT_ARTIFACTS}"
        env:
          VAGRANT_ARTIFACTS: ${{ steps.names.outputs.artifacts-path }}
          CACHE_ID: ${{ steps.commit.outputs.vagrant-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Ruby
        if: steps.commit.outputs.vagrant-cache-exists != 'true'
        uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # v1.180.1
        with:
          ruby-version: '3.1'
      - name: Setup Go
        if: steps.commit.outputs.vagrant-cache-exists != 'true'
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
      - name: Build Vagrant Artifacts
        if: steps.commit.outputs.vagrant-cache-exists != 'true'
        run: ./vagrant-source/.ci/build "${VAGRANT_ARTIFACTS}"
        env:
          VAGRANT_ARTIFACTS: ${{ steps.names.outputs.artifacts-path }}
      - name: Cache Vagrant Artifacts
        if: steps.commit.outputs.vagrant-cache-exists != 'true'
        run: ./.ci/create-cache "${CACHE_ID}" "${VAGRANT_ARTIFACTS}"
        env:
          VAGRANT_ARTIFACTS: ${{ steps.names.outputs.artifacts-path }}
          CACHE_ID: ${{ steps.commit.outputs.vagrant-cache-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Vagrant Information
        id: info
        run: ./.ci/fetch-vagrant-info "${VAGRANT_ARTIFACTS}"
        env:
          VAGRANT_ARTIFACTS: ${{ steps.names.outputs.artifacts-path }}
      - name: Generate Package License Files
        run: |
          mkdir -p "${VAGRANT_LICENSES}" || exit 1
          cp ./vagrant-source/templates/license/license.tmpl "${VAGRANT_LICENSES}/LICENSE.txt" || exit 1
          cp ./vagrant-source/templates/license/license.html.tmpl "${VAGRANT_LICENSES}/LICENSE.html" || exit 1
          cp ./vagrant-source/templates/license/license.rtf.tmpl "${VAGRANT_LICENSES}/LICENSE.rtf" || exit 1
        env:
          VAGRANT_LICENSES: ${{ steps.names.outputs.licenses-path }}
      - name: Upload Vagrant Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ steps.names.outputs.artifacts-name }}
          path: ${{ steps.names.outputs.artifacts-path }}
      - name: Isolate Vagrant RubyGem
        run: |
          mkdir gem
          cp "${VAGRANT_ARTIFACTS}/"vagrant*.gem "${VAGRANT_GEM_PATH}/vagrant.gem"
        env:
          VAGRANT_ARTIFACTS: ${{ steps.names.outputs.artifacts-path }}
          VAGRANT_GEM_PATH: ${{ steps.names.outputs.gem-path }}
      - name: Upload Vagrant RubyGem
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ steps.names.outputs.gem-name }}
          path: ${{ steps.names.outputs.gem-path }}
      - name: Upload Vagrant Licenses
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ${{ steps.names.outputs.licenses-name }}
          path: ${{ steps.names.outputs.licenses-path }}
