name: VagrantCloud Vars

on:
  workflow_call:
    outputs:
      VAGRANT_CLOUD_TOKEN:
        value: ${{ jobs.get-vars.outputs.VAGRANT_CLOUD_TOKEN }}

jobs:
  get-vars:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    outputs:
      VAGRANT_CLOUD_TOKEN: ${{ steps.vars.outputs.VAGRANT_CLOUD_TOKEN }}
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Fetch vars
        id: vars
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificates: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/${{ github.repository }} vagrant_cloud_token | VAGRANT_CLOUD_TOKEN;
